# The base hadoop image to use for all components.
postgresql:
  global:
    postgresql:
      auth:
        username: hive
        password: hive
        database: metastore

  # For easy deployment don't use persistent volumes. Obviously, not proper
  # for production release
  primary:
    persistence:
      enabled: false

# Settings for the hive metastore stateful set
image:
  repository: naushadh/hive-metastore
  tag: latest
  pullPolicy: IfNotPresent

resources: {}
conf:
  hiveSite:
    hive_metastore_uris: thrift://hive-metastore:9083
    # if not set, default hive.metastore.warehouse.dir is default to: "hdfs://{{.Release.Name}}-hdfs:8020/user/hive/warehouse"
    # hive.metastore.warehouse.dir:
